var fs = require("fs");
const path = require("path");

var data = [
  "https://i.imgur.com/U1CyEuA.jpg",
  "https://i.imgur.com/HBVrdaj.jpg",
  "https://i.imgur.com/701RLfV.jpg",
  "https://i.imgur.com/tKUi6Rf.jpg",
  "https://i.imgur.com/op8BVph.jpg",
  "https://i.imgur.com/G2YvPHf.jpg",
  "https://i.imgur.com/U1CyEuA.jpg",
  "https://i.imgur.com/nsvNixW.jpg",
  "https://i.imgur.com/QPpjPac.jpg",
  "https://i.imgur.com/wjlDigg.jpg",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/1Atixoj.gif",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/eWWi3gZ.gif",
  "https://i.imgur.com/1Atixoj.gif",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/1Atixoj.gif",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/1Atixoj.gif",
  "https://i.imgur.com/MJAkxbh.png",
  "https://i.imgur.com/1Atixoj.gif",
  "https://i.imgur.com/aa8oGgP.png",
  "https://i.stack.imgur.com/4bz2N.png",
  "https://i.stack.imgur.com/5LZ9V.png",
  "https://i.imgur.com/QAuugOL.jpg",
  "https://i.imgur.com/1710fEx.jpg",
  "https://i.imgur.com/jr4icze.jpg",
  "https://i.imgur.com/W57lGsk.jpg",
  "https://i.imgur.com/5Twm8NE.jpg",
  "https://i.imgur.com/01xetay.jpg",
  "https://i.imgur.com/ThkzYEV.jpg",
  "https://i.imgur.com/K7HfCly.jpg",
  "https://i.imgur.com/ZOSxeZD.jpg",
  "https://i.imgur.com/SwKsPxD.jpg",
  "https://i.imgur.com/3AaViff.jpg",
  "https://i.imgur.com/RMTqXPw.png",
  "https://i.stack.imgur.com/59Rpw.png",
  "https://i.imgur.com/FwZuFGy.png",
  "https://i.imgur.com/d1liGwI.png",
  "https://imgur.com/SiU8uTe.png",
  "https://i.imgur.com/Pb0aTkV.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/2uGfleD.jpg",
  "https://i.imgur.com/CvtXCMd.jpg",
  "https://i.imgur.com/e4dRvZR.jpg",
  "https://i.imgur.com/k4FSyXz.jpg",
  "https://i.imgur.com/YvtbUBH.jpg",
  "https://i.imgur.com/8gKRhAp.jpg",
  "https://i.imgur.com/lFJaBUfh.png",
  "https://i.imgur.com/4X8ITZih.png",
  "https://i.imgur.com/wPqUgsih.png",
  "https://i.imgur.com/7n0V1G4h.png",
  "https://i.imgur.com/pa4grM8h.png",
  "https://i.imgur.com/6Z2VStD.png ",
  "https://imgur.com/sczZjwm.gif",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/zoMspyn.png",
  "https://i.imgur.com/3d9SqBR.png",
  "https://i.imgur.com/rnQEY7o.png",
  "https://i.imgur.com/jrnu6mE.png",
  "https://i.imgur.com/gszPtRa.png",
  "https://i.imgur.com/TKXxZGF.png",
  "https://i.imgur.com/qQGOiyC.png ",
  "https://i.imgur.com/uDbypks.png ",
  "https://i.imgur.com/u7dfnuA.png ",
  "https://i.imgur.com/6x8Z0pj.png ",
  "https://i.imgur.com/8EsVvZk.png ",
  "https://i.imgur.com/V2JzAka.png ",
  "https://i.imgur.com/KUeOSK3.png",
  "https://i.imgur.com/SOhv2jZ.png",
  "https://i.stack.imgur.com/gCaz3.png",
  "https://i.imgur.com/YXzUPiB.png",
  "https://i.imgur.com/AQ3P4vi.png",
  "https://i.imgur.com/ZErXKtQ.png",
  "https://i.imgur.com/fN5wOH2.png",
  "https://i.imgur.com/4ji7JXx.png",
  "https://i.imgur.com/1tPHKHj.png",
  "https://i.stack.imgur.com/jRaTj.jpg?s=128&g=1",
  "https://i.imgur.com/l8EAw1L.png ",
  "https://i.imgur.com/pfC7QFH.png ",
  "https://i.imgur.com/b4vFsKa.png",
  "https://i.imgur.com/uRLunzU.png",
  "https://i.imgur.com/pZij95O.jpg",
  "https://i.imgur.com/vlV7ZFr.png",
  "https://i.imgur.com/9ILjA1q.jpg",
  "https://i.imgur.com/V5nP3xj.jpg",
  "https://i.imgur.com/DznuAou.jpg",
  "https://i.imgur.com/O16uc8E.png",
  "https://i.imgur.com/AyvSsLk.png",
  "https://i.imgur.com/4RY0hVu.png",
  "https://i.imgur.com/hsEjqfm.png",
  "https://i.imgur.com/aa8oGgP.png",
  "https://i.stack.imgur.com/4bz2N.png",
  "https://i.stack.imgur.com/5LZ9V.png",
  "https://i.imgur.com/QAuugOL.jpg",
  "https://i.imgur.com/1710fEx.jpg",
  "https://i.imgur.com/jr4icze.jpg",
  "https://i.imgur.com/W57lGsk.jpg",
  "https://i.imgur.com/5Twm8NE.jpg",
  "https://i.imgur.com/01xetay.jpg",
  "https://i.imgur.com/ThkzYEV.jpg",
  "https://i.imgur.com/K7HfCly.jpg",
  "https://i.imgur.com/ZOSxeZD.jpg",
  "https://i.imgur.com/SwKsPxD.jpg",
  "https://i.imgur.com/3AaViff.jpg",
  "https://i.imgur.com/RMTqXPw.png",
  "https://i.stack.imgur.com/59Rpw.png",
  "https://i.imgur.com/FwZuFGy.png",
  "https://i.imgur.com/d1liGwI.png",
  "https://imgur.com/SiU8uTe.png",
  "https://i.imgur.com/Pb0aTkV.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/2uGfleD.jpg",
  "https://i.imgur.com/CvtXCMd.jpg",
  "https://i.imgur.com/e4dRvZR.jpg",
  "https://i.imgur.com/k4FSyXz.jpg",
  "https://i.imgur.com/YvtbUBH.jpg",
  "https://i.imgur.com/8gKRhAp.jpg",
  "https://i.imgur.com/lFJaBUfh.png",
  "https://i.imgur.com/4X8ITZih.png",
  "https://i.imgur.com/wPqUgsih.png",
  "https://i.imgur.com/7n0V1G4h.png",
  "https://i.imgur.com/pa4grM8h.png",
  "https://i.imgur.com/6Z2VStD.png ",
  "https://imgur.com/sczZjwm.gif",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/zoMspyn.png",
  "https://i.imgur.com/3d9SqBR.png",
  "https://i.imgur.com/rnQEY7o.png",
  "https://i.imgur.com/jrnu6mE.png",
  "https://i.imgur.com/gszPtRa.png",
  "https://i.imgur.com/TKXxZGF.png",
  "https://i.imgur.com/8EsVvZk.png",
  "https://i.imgur.com/V2JzAka.png ",
  "https://i.imgur.com/KUeOSK3.png",
  "https://i.imgur.com/SOhv2jZ.png",
  "https://i.stack.imgur.com/gCaz3.png",
  "https://i.imgur.com/YXzUPiB.png",
  "https://i.imgur.com/AQ3P4vi.png",
  "https://i.imgur.com/ZErXKtQ.png",
  "https://i.imgur.com/fN5wOH2.png",
  "https://i.imgur.com/4ji7JXx.png",
  "https://i.imgur.com/1tPHKHj.png",
  "https://i.imgur.com/RqgGcf5.gif",
  "https://i.stack.imgur.com/jRaTj.jpg?s=128&g=1",
  "https://i.imgur.com/l8EAw1L.png",
  "https://i.imgur.com/pfC7QFH.png ",
  "https://i.imgur.com/b4vFsKa.png",
  "https://i.imgur.com/uRLunzU.png",
  "https://i.imgur.com/pZij95O.jpg",
  "https://i.imgur.com/vlV7ZFr.png",
  "https://i.imgur.com/9ILjA1q.jpg",
  "https://i.imgur.com/V5nP3xj.jpg",
  "https://i.imgur.com/DznuAou.jpg",
  "https://i.imgur.com/O16uc8E.png",
  "https://i.imgur.com/AyvSsLk.png",
  "https://i.imgur.com/4RY0hVu.png",
  "https://i.imgur.com/hsEjqfm.png",
  "https://i.imgur.com/msFhj0x.png ",
  "https://i.imgur.com/ZI8P3Qx.png",
  "https://i.imgur.com/aa8oGgP.png  ",
  "https://i.stack.imgur.com/4bz2N.png",
  "https://i.stack.imgur.com/5LZ9V.png",
  "https://i.imgur.com/QAuugOL.jpg",
  "https://i.imgur.com/1710fEx.jpg",
  "https://i.imgur.com/jr4icze.jpg",
  "https://i.imgur.com/W57lGsk.jpg",
  "https://i.imgur.com/5Twm8NE.jpg",
  "https://i.imgur.com/01xetay.jpg",
  "https://i.imgur.com/ThkzYEV.jpg",
  "https://i.imgur.com/K7HfCly.jpg",
  "https://i.imgur.com/ZOSxeZD.jpg",
  "https://i.imgur.com/SwKsPxD.jpg",
  "https://i.imgur.com/3AaViff.jpg",
  "https://i.imgur.com/W6QaUAX.png",
  "https://i.imgur.com/1UUFXnM.png",
  "https://i.imgur.com/Lih2m92.png",
  "https://i.imgur.com/mEvXx3A.png",
  "https://i.imgur.com/tYzAJK1.png",
  "https://i.imgur.com/oQc1SKK.png",
  "https://i.imgur.com/RMTqXPw.png",
  "https://i.stack.imgur.com/59Rpw.png",
  "https://i.imgur.com/FwZuFGy.png",
  "https://imgur.com/SiU8uTe.png",
  "https://i.imgur.com/Pb0aTkV.png",
  "https://i.imgur.com/daIlXQI.png ",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/2uGfleD.jpg",
  "https://i.imgur.com/CvtXCMd.jpg",
  "https://i.imgur.com/e4dRvZR.jpg",
  "https://i.imgur.com/k4FSyXz.jpg",
  "https://i.imgur.com/YvtbUBH.jpg",
  "https://i.imgur.com/8gKRhAp.jpg",
  "https://i.imgur.com/lFJaBUfh.png",
  "https://i.imgur.com/4X8ITZih.png",
  "https://i.imgur.com/wPqUgsih.png",
  "https://i.imgur.com/7n0V1G4h.png",
  "https://i.imgur.com/pa4grM8h.png",
  "https://i.imgur.com/S0QPDi4.png",
  "https://i.imgur.com/6Z2VStD.png",
  "https://imgur.com/sczZjwm.gif",
  "https://imgur.com/Yl0Bxwn",
  "https://imgur.com/wgscRNa",
  "https://i.imgur.com/ToWQjHO.png",
  "https://i.imgur.com/eULdyep.png",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/r0br52L.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/zoMspyn.png",
  "https://i.imgur.com/3d9SqBR.png",
  "https://i.imgur.com/rnQEY7o.png",
  "https://i.imgur.com/jrnu6mE.png",
  "https://i.imgur.com/gszPtRa.png",
  "https://i.imgur.com/TKXxZGF.png",
  "https://i.imgur.com/8EsVvZk.png",
  "https://i.imgur.com/V2JzAka.png",
  "https://i.imgur.com/KUeOSK3.png",
  "https://i.imgur.com/SOhv2jZ.png",
  "https://i.stack.imgur.com/gCaz3.png",
  "https://i.stack.imgur.com/ALoC9.png",
  "https://i.imgur.com/YXzUPiB.png",
  "https://i.imgur.com/AQ3P4vi.png",
  "https://i.imgur.com/ZErXKtQ.png",
  "https://i.imgur.com/fN5wOH2.png",
  "https://i.imgur.com/4ji7JXx.png",
  "https://i.imgur.com/1tPHKHj.png",
  "https://i.imgur.com/RqgGcf5.gif",
  "https://i.stack.imgur.com/jRaTj.jpg?s=128&g=1",
  "https://i.imgur.com/l8EAw1L.png ",
  "https://i.imgur.com/W3amiIr.png",
  "https://i.imgur.com/5ys9G3k.png",
  "https://i.imgur.com/Jq0eKrO.jpg",
  "https://i.imgur.com/3ALtws1.png",
  "https://i.imgur.com/Jk2aJod.png",
  "https://i.imgur.com/fassWYs.png",
  "https://i.imgur.com/H9mO8qS.jpg",
  "https://i.imgur.com/woj5vPm.png",
  "https://i.imgur.com/halOgkj.png",
  "https://i.imgur.com/b4vFsKa.png",
  "https://i.imgur.com/uRLunzU.png",
  "https://i.imgur.com/pZij95O.jpg",
  "https://i.imgur.com/vlV7ZFr.png",
  "https://i.imgur.com/9ILjA1q.jpg",
  "https://i.imgur.com/V5nP3xj.jpg",
  "https://i.imgur.com/DznuAou.jpg",
  "https://i.imgur.com/O16uc8E.png",
  "https://i.imgur.com/AyvSsLk.png",
  "https://i.imgur.com/4RY0hVu.png",
  "https://i.imgur.com/hsEjqfm.png",
  "https://i.imgur.com/aa8oGgP.png",
  "https://i.stack.imgur.com/4bz2N.png",
  "https://i.stack.imgur.com/5LZ9V.png",
  "https://i.imgur.com/QAuugOL.jpg",
  "https://i.imgur.com/1710fEx.jpg",
  "https://i.imgur.com/jr4icze.jpg",
  "https://i.imgur.com/W57lGsk.jpg",
  "https://i.imgur.com/5Twm8NE.jpg",
  "https://i.imgur.com/01xetay.jpg",
  "https://i.imgur.com/ThkzYEV.jpg",
  "https://i.imgur.com/K7HfCly.jpg",
  "https://i.imgur.com/ZOSxeZD.jpg",
  "https://i.imgur.com/SwKsPxD.jpg",
  "https://i.imgur.com/3AaViff.jpg",
  "https://i.imgur.com/RMTqXPw.png",
  "https://i.stack.imgur.com/59Rpw.png",
  "https://i.imgur.com/FwZuFGy.png",
  "https://i.imgur.com/d1liGwI.png",
  "https://imgur.com/SiU8uTe.png",
  "https://i.imgur.com/Pb0aTkV.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/2uGfleD.jpg",
  "https://i.imgur.com/CvtXCMd.jpg",
  "https://i.imgur.com/e4dRvZR.jpg",
  "https://i.imgur.com/k4FSyXz.jpg",
  "https://i.imgur.com/YvtbUBH.jpg",
  "https://i.imgur.com/8gKRhAp.jpg",
  "https://i.imgur.com/lFJaBUfh.png",
  "https://i.imgur.com/4X8ITZih.png",
  "https://i.imgur.com/wPqUgsih.png",
  "https://i.imgur.com/7n0V1G4h.png",
  "https://i.imgur.com/pa4grM8h.png",
  "https://i.imgur.com/6Z2VStD.png ",
  "https://imgur.com/sczZjwm.gif",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/zoMspyn.png",
  "https://i.imgur.com/3d9SqBR.png",
  "https://i.imgur.com/rnQEY7o.png",
  "https://i.imgur.com/jrnu6mE.png",
  "https://i.imgur.com/gszPtRa.png",
  "https://i.imgur.com/TKXxZGF.png",
  "https://i.imgur.com/8EsVvZk.png ",
  "https://i.imgur.com/V2JzAka.png ",
  "https://i.imgur.com/KUeOSK3.png",
  "https://i.imgur.com/SOhv2jZ.png",
  "https://i.stack.imgur.com/gCaz3.png ",
  "https://i.imgur.com/YXzUPiB.png",
  "https://i.imgur.com/AQ3P4vi.png",
  "https://i.imgur.com/ZErXKtQ.png",
  "https://i.imgur.com/fN5wOH2.png",
  "https://i.imgur.com/4ji7JXx.png",
  "https://i.imgur.com/1tPHKHj.png",
  "https://i.imgur.com/RqgGcf5.gif",
  "https://i.stack.imgur.com/jRaTj.jpg?s=128&g=1 ",
  "https://i.imgur.com/l8EAw1L.png ",
  "https://i.imgur.com/pfC7QFH.png ",
  "https://i.imgur.com/b4vFsKa.png",
  "https://i.imgur.com/uRLunzU.png",
  "https://i.imgur.com/pZij95O.jpg",
  "https://i.imgur.com/vlV7ZFr.png",
  "https://i.imgur.com/9ILjA1q.jpg",
  "https://i.imgur.com/V5nP3xj.jpg",
  "https://i.imgur.com/DznuAou.jpg",
  "https://i.imgur.com/O16uc8E.png",
  "https://i.imgur.com/AyvSsLk.png",
  "https://i.imgur.com/4RY0hVu.png",
  "https://i.imgur.com/hsEjqfm.png",
  "https://i.imgur.com/aa8oGgP.png",
  "https://i.stack.imgur.com/4bz2N.png",
  "https://i.stack.imgur.com/5LZ9V.png",
  "https://i.imgur.com/QAuugOL.jpg",
  "https://i.imgur.com/1710fEx.jpg",
  "https://i.imgur.com/jr4icze.jpg",
  "https://i.imgur.com/W57lGsk.jpg",
  "https://i.imgur.com/5Twm8NE.jpg",
  "https://i.imgur.com/01xetay.jpg",
  "https://i.imgur.com/ThkzYEV.jpg",
  "https://i.imgur.com/K7HfCly.jpg",
  "https://i.imgur.com/ZOSxeZD.jpg",
  "https://i.imgur.com/SwKsPxD.jpg",
  "https://i.imgur.com/3AaViff.jpg",
  "https://i.imgur.com/RMTqXPw.png",
  "https://i.stack.imgur.com/59Rpw.png",
  "https://i.imgur.com/FwZuFGy.png",
  "https://i.imgur.com/d1liGwI.png",
  "https://imgur.com/SiU8uTe.png",
  "https://i.imgur.com/Pb0aTkV.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/2uGfleD.jpg",
  "https://i.imgur.com/CvtXCMd.jpg",
  "https://i.imgur.com/e4dRvZR.jpg",
  "https://i.imgur.com/k4FSyXz.jpg",
  "https://i.imgur.com/YvtbUBH.jpg",
  "https://i.imgur.com/8gKRhAp.jpg",
  "https://i.imgur.com/lFJaBUfh.png",
  "https://i.imgur.com/4X8ITZih.png",
  "https://i.imgur.com/wPqUgsih.png",
  "https://i.imgur.com/7n0V1G4h.png",
  "https://i.imgur.com/pa4grM8h.png",
  "https://i.imgur.com/6Z2VStD.png",
  "https://imgur.com/sczZjwm.gif",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/zoMspyn.png",
  "https://i.imgur.com/3d9SqBR.png",
  "https://i.imgur.com/rnQEY7o.png",
  "https://i.imgur.com/jrnu6mE.png",
  "https://i.imgur.com/gszPtRa.png",
  "https://i.imgur.com/TKXxZGF.png",
  "https://i.imgur.com/8EsVvZk.png",
  "https://i.imgur.com/V2JzAka.png",
  "https://i.imgur.com/KUeOSK3.png",
  "https://i.imgur.com/SOhv2jZ.png",
  "https://i.stack.imgur.com/gCaz3.png ",
  "https://i.imgur.com/YXzUPiB.png",
  "https://i.imgur.com/AQ3P4vi.png",
  "https://i.imgur.com/ZErXKtQ.png",
  "https://i.imgur.com/fN5wOH2.png",
  "https://i.imgur.com/4ji7JXx.png",
  "https://i.imgur.com/1tPHKHj.png",
  "https://i.imgur.com/RqgGcf5.gif",
  "https://i.stack.imgur.com/jRaTj.jpg?s=128&g=1",
  "https://i.imgur.com/l8EAw1L.png",
  "https://i.imgur.com/pfC7QFH.png",
  "https://i.imgur.com/b4vFsKa.png",
  "https://i.imgur.com/uRLunzU.png",
  "https://i.imgur.com/pZij95O.jpg",
  "https://i.imgur.com/vlV7ZFr.png",
  "https://i.imgur.com/9ILjA1q.jpg",
  "https://i.imgur.com/V5nP3xj.jpg",
  "https://i.imgur.com/DznuAou.jpg",
  "https://i.imgur.com/O16uc8E.png",
  "https://i.imgur.com/AyvSsLk.png",
  "https://i.imgur.com/4RY0hVu.png",
  "https://i.imgur.com/hsEjqfm.png",
  "https://i.imgur.com/aa8oGgP.png",
  "https://i.stack.imgur.com/4bz2N.png",
  "https://i.stack.imgur.com/5LZ9V.png",
  "https://i.imgur.com/QAuugOL.jpg",
  "https://i.imgur.com/1710fEx.jpg",
  "https://i.imgur.com/jr4icze.jpg",
  "https://i.imgur.com/W57lGsk.jpg",
  "https://i.imgur.com/5Twm8NE.jpg",
  "https://i.imgur.com/01xetay.jpg",
  "https://i.imgur.com/ThkzYEV.jpg",
  "https://i.imgur.com/K7HfCly.jpg",
  "https://i.imgur.com/ZOSxeZD.jpg",
  "https://i.imgur.com/SwKsPxD.jpg",
  "https://i.imgur.com/3AaViff.jpg",
  "https://i.imgur.com/RMTqXPw.png",
  "https://i.stack.imgur.com/59Rpw.png",
  "https://i.imgur.com/FwZuFGy.png",
  "https://i.imgur.com/d1liGwI.png",
  "https://imgur.com/SiU8uTe.png",
  "https://i.imgur.com/Pb0aTkV.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/YdbgWHL.png",
  "https://i.imgur.com/2uGfleD.jpg",
  "https://i.imgur.com/CvtXCMd.jpg",
  "https://i.imgur.com/e4dRvZR.jpg",
  "https://i.imgur.com/k4FSyXz.jpg",
  "https://i.imgur.com/YvtbUBH.jpg",
  "https://i.imgur.com/8gKRhAp.jpg",
  "https://i.imgur.com/lFJaBUfh.png",
  "https://i.imgur.com/4X8ITZih.png",
  "https://i.imgur.com/wPqUgsih.png",
  "https://i.imgur.com/7n0V1G4h.png",
  "https://i.imgur.com/pa4grM8h.png",
  "https://i.imgur.com/6Z2VStD.png",
  "https://imgur.com/sczZjwm.gif",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/zoMspyn.png",
  "https://i.imgur.com/3d9SqBR.png",
  "https://i.imgur.com/rnQEY7o.png",
  "https://i.imgur.com/jrnu6mE.png",
  "https://i.imgur.com/gszPtRa.png",
  "https://i.imgur.com/TKXxZGF.png",
  "https://i.imgur.com/8EsVvZk.png",
  "https://i.imgur.com/V2JzAka.png",
  "https://i.imgur.com/KUeOSK3.png",
  "https://i.imgur.com/SOhv2jZ.png",
  "https://i.stack.imgur.com/gCaz3.png ",
  "https://i.imgur.com/YXzUPiB.png",
  "https://i.imgur.com/AQ3P4vi.png",
  "https://i.imgur.com/ZErXKtQ.png",
  "https://i.imgur.com/fN5wOH2.png",
  "https://i.imgur.com/4ji7JXx.png",
  "https://i.imgur.com/1tPHKHj.png",
  "https://i.imgur.com/RqgGcf5.gif",
  "https://i.stack.imgur.com/jRaTj.jpg?s=128&g=1 ",
  "https://i.imgur.com/l8EAw1L.png ",
  "https://i.imgur.com/pfC7QFH.png ",
  "https://i.imgur.com/b4vFsKa.png",
  "https://i.imgur.com/uRLunzU.png",
  "https://i.imgur.com/pZij95O.jpg",
  "https://i.imgur.com/vlV7ZFr.png",
  "https://i.imgur.com/9ILjA1q.jpg",
  "https://i.imgur.com/V5nP3xj.jpg",
  "https://i.imgur.com/DznuAou.jpg",
  "https://i.imgur.com/O16uc8E.png",
  "https://i.imgur.com/AyvSsLk.png",
  "https://i.imgur.com/4RY0hVu.png",
  "https://i.imgur.com/hsEjqfm.png",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png",
  "https://i.imgur.com/EkjwJdr.png",
  "https://i.imgur.com/Z1DSMYC.png"
];

console.log("hello");
data = [...new Set(data)];
console.log(data);

fs.writeFile("uniqueUrls.js", data, "utf8", function(err) {
  if (err) {
    console.log("An error occured while writing JSON Object to File.");
    return console.log(err);
  }

  console.log("JSON file has been saved.");
});

//   var jsonData = `{"urls":[${data}]}`;

//   var jsonObj = JSON.parse(jsonData);
//   console.log(jsonObj);

//   // stringify JSON Object
//   var jsonContent = JSON.stringify(jsonObj);
//   console.log(jsonContent);

//   fs.writeFile("uniqueUrls.json", jsonContent, "utf8", function(err) {
//     if (err) {
//       console.log("An error occured while writing JSON Object to File.");
//       return console.log(err);
//     }

//     console.log("JSON file has been saved.");
//   });
